version: "3"
services:
  proxy:
    image: ubuntu/squid
    ports:
      - "28080:3128"
    volumes:
      - ./squid.conf.auth:/etc/squid/squid.conf
      - ./passwords:/etc/squid/passwords
    restart: always
